# Generated by Django 6.0.4 on 2026-04-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationproposal',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='itineraryactivity',
            name='place_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
