# Generated by Django 6.0.4 on 2026-04-19 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_destinationproposal_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='sync.destinationproposal'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='sync.trip'),
        ),
    ]
