# Generated by Django 6.0.4 on 2026-04-19 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_itinerary_proposal_alter_itinerary_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='confirmed_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sync.destinationproposal'),
        ),
    ]
